version: '2'
services:
  library-app:
    image: library
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://library-postgresql:5432/library
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  library-postgresql:
    extends:
      file: postgresql.yml
      service: library-postgresql
